language: python
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

matrix:
  include:
    #- env: TOXENV=check
    #  python: 3.6
    #- env: TOXENV=docs
    #  python: 3.6
    #- env: TOXENV=py26,codecov
    #  python: 2.6
    - env: TOXENV=py27
      python: 2.7
    #- env: TOXENV=py34,codecov
    #  python: 3.4
    #- env: TOXENV=py35,codecov
    #  python: 3.5
    - env: TOXENV=py36
      python: 3.6
    #- env: TOXENV=pypy,codecov
    #  python: pypy

before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install --upgrade tox setuptools wheel virtualenv
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
#notifications:
  #email:
  #  on_success: never
  #  on_failure: always
  #slack:
  #  rooms:
  #    - secure: nsbTI19SAiog6V6OnN1diYU2V3RIwtmY+IqV4uAvki87dQZteWU22/kQ0wI0OZAOzvEG3lLrc7ZGnbKh+IiH3QJkAwwHgtgC2zdzy6EGkjyEQpeAFUujaEHcRKEIpeAdtNpSUTrPsywdbnT6sO4XN/S7ZhSxS3TRmL2Wi399i36/D0T7gt/GAcPdxrFKwZ20PN20By+5j54FO6/X7y0IVcoUgKdYIvP5NGILRyo+tlWP6dJKFeuxT7lU3FV6W7J7DQs/2yjwH1naBmulxWp22+wNopJ1loW9PHtsJzlN0kUp1Up/+pwHvr7bVbZBzXSZZ5V7j+Xi7uh0de8GYckg0ATJTvrB5c1KZaG9p2unhyMlVAyDfNez3LtgUERnd7S1YXxz8JwbyWlEodzKO/dcnA1PkzcPECEbeXQJtxdhXuz+8pVqIAkDejCv4bhZVUtC4beeQFjxTrqKewxMNpTKKCacIWEBLrCUzr4y15qy7ziRU8CPvFkaUYBkPSWIOp2Xv7FOBwlEhR8d5P6P2eJ7P1vbYVB1vvrYgo0Z4pQkaM02E2/YgSoEfpWsgrSNS+9W0aQtAxcIg6ilY4ZcY83xAmwa8W7uILygqqK0Q7m+UiirIePMWXJ3r9MNkpHHlEr+WebFQYYNhOqVDJ5oX1+KKZY91bJl0ozqUvy4KSlBPO8=
  #  on_success: never
  #  on_failure: always

# After you create the Github repo and add it to Travis, run the
# ci/travis_pypi_setup.py script and set the secure passwords to
# finish PyPI deployment setup
before_deploy:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      export VERSION=$(grep "version = " $TRAVIS_BUILD_DIR/setup.cfg | sed "s/version = //")
      export BODY="* Mjukvaruläge v$VERSION Body - This is a good place for a changelog link."
      echo "VERSION=$VERSION"
      echo "BODY=$BODY"
      echo "TRAVIS_COMMIT=$TRAVIS_COMMIT"
      (set -x; git tag -a $VERSION -m $VERSION)
    fi
  # Prep to create standalone
  # Install dependencies
  # Install watchmaker
  #- pip install --editable .
  #- pwd
  #- env
  #- cp $VIRTUAL_ENV/bin/watchmaker ./standalone/watchmaker-script.py
  #- cd ./standalone
  #- pwd
  #- ls -hal
  #- python generate-standalone.py
  #- ls -hal
deploy:
  - provider: script
    script: python release_script.py
    xyzabc: $VERSION
    skip_cleanup: true
    on:
      branch: master
      repo: YakDriver/mjukvarulage
      condition: '"$TOXENV" == *"py36"*'
  #- provider: pypi
  #  server: https://test.pypi.org/legacy/
  #  distributions: sdist bdist_wheel
  #  user: plus3it
  #  password:
  #    secure: o1r3jJSHXoh+QjgYi0FCP3GAOJtEsgGdnW/oKYLCPfW9CQoSHXTZtH5MAYmyOT5c9TQLqKxMtQHu8rRx5ZQoAe5WOmdhzc85c01qMcbC0DW1LaSibGM3oqqDtPFEipoFry3CpJLVIURE2lRV56DJtfTv43DIrUpgwrGU1+ijtCWZdcEzQUizvNKpX+K5jGHty9zyUHnaMx/OiM16loVDeue1Ukh++aTEEW0dqk2eAhN8ihZc0uAhls4DcQgN6R+bLXoR7oBk84QzQtxJlNS6CQcVltmtWA2ARxVV6CUpEr/JegufdNI7/Vdg4THg0g/iu0TatfJy1m2MDopUWSGrUOz8BQRCw1reRwWfPjhvuU0Ny+EINl3cnER2CJ67njo9PRjH0bDFcJQe6umPU7lf3dUOvbXGWeEAYaF1BOn490K9XNpOqw4XcGtjnm3c4YBTSuCp95APji7G8HlWtN54K1UWFZN48IkvKW3WbZX95BgLB3131yITwBdnNaPHm7sgI1OS7V3+/T8eNr5EDXTvunVt0olPuWzcWuLVmRq6/qVwdrko9MHOsmgMSFJi/QNGF23XjfT+9Aa0MP8iGpEZF5b8ZeB0qHdeugw0uMDSZ87msR9wCbgcTCbub89/ZmNCbyqIUTWyarCTtXJ9ARrVqwjrAsTSP78wfizthAqHUt4=
  #  skip_cleanup: true
  #  skip_upload_docs: true
  #  on:
  #    branch: develop
  #    repo: plus3it/watchmaker
  #    condition: '"$TOXENV" == *"py27"*'
  #- provider: pypi
  #  distributions: sdist bdist_wheel
  #  user: plus3it
  #  password:
  #    secure: QBRj35p/WVBbfXWsOGaQfZ5LxLo2h/44iJRKaGkqAc/l7fNPubUcvKTvsuvFKDS68wdacnvSPifhVjJB8B/UwDyk3WqWmm/e7MBpWAJhZUina9qceeB7IPO53zSnfD8xAJMBe7iWRnMAQaKpPerSOKPpGn5qkdvfQXWhYHLe1X70RWVSkJlr35kkpBDvcqkKvKCi9EGrkJMbS+px/97n+b86wGKO0T8s2+YKAUh3EN9IHo6r9pG36uME2SCXqfhu9MH9aSlBLirOKvbvH+eVpOtAF+AfSsstMYFD2MbWEDYnXDrav4dqielk9o+Z2jaWvHAwBhCPp3aKYEx+xKrVsgu+9wE5e9i0T1CUPZSpeYkc+qPIjTZLmUpR9S32M19QmyewwyWPXHLD5TlFeHgU+/n0Y+dWJwBUESK58THvAXSewsTOhePEs+zuQfKXUFHHYYM+uJ020X3lv/R5SziSl93eD7nWuulBHwzBF3FEPiQnfrv1Ns0E28zdrkDJ6IxYES0tfHOHdFQZlSwGe8JJgzoXm2jtClJB/wkn/TwwInX7CvlgrVNrNDcHTGBiUoncb/yy6aIIR2DsCjYxd1WMN12DpaY+4OonDik/Ot4DcLiE1CA7b+1TKsbAv3G2YuFBp4QUBellnAU/L8wBxhgmhLTCntAQmPYuWezztRwEyG8=
  #  skip_upload_docs: true
  #  on:
  #    tags: true
  #    repo: plus3it/watchmaker
  #    condition: '"$TOXENV" == *"py27"*'
  #- provider: releases
  #  name: $WAM_VERSION
  #  tag_name: $WAM_VERSION
  #  target_commitish: $TRAVIS_COMMIT
  #  body: $WAM_BODY
  #  draft: false
  #  skip_cleanup: true
  #  api_key:
  #    secure: OaLLCA68gPQOA19yNS/0dGOLODvUM5cPEtz3n0y1cyYtfEP7B5Lv9ZmjQlSO9p0nAw/0im07xn99egUAed7J45i58bXYaC+p7yBCLW6tsKdQx5Jr6nI9D+ztMlzHB2EaLLn8q7pW8uFvtUZTAi41+2DHPIYNTDBaPYzxuXhieXH4o1spXfLoLe+ETG3YLUXbaI48V55PCH7RVjHwGrJfvRjQQppyvK0580ZHc0Y914l5DdUlrDUwxMo3yp+SpJErSedqQpSaQ1OOziMinR4NtIQWrpjB0cxpOvfbsMtfMXJV54fWNT/7lOA0Xok0rHji8zttqvPrqq8C1wj8Dcj7V7N7dtmoGPKsVJ2RaVFjZ8aWPew/o7bA4S9S8NtkhJxHV3Uvn/HQrCePqCdn0T7s72XgK3FB2fZlBJwRDHBqfXVEYvFvu+85lZV2QcDeIyEZXLK6CjCSUh2GL1Du9VWFKd0VvjI34CVIRXr5wRTMTlt0KOSMBR2IxugMn1yA25Ek0M2c5e1YbO7/wZPPKPUdQJSeEyEo0XWGAp2D9zEJY5eRVkkcAY8wSbAedIWnjaieb1OR4ql3BRracFezhsF2ajmUqbiXobG26hmt2Br2cn+6bzQ7L6F43xAHsQQkJQ1w+hsyXpl7De0EbFaCfVNS+PUDV7xWrtcOfIYV/UKo2Qk=
  #  on:
  #    branch: standalone
  #    repo: YakDriver/watchmaker
  #    condition: '"$TOXENV" == *"py27"*'
  #- provider: releases
    #name: $WAM_VERSION
    #tag_name: $WAM_VERSION
    #target_commitish: $TRAVIS_COMMIT
    #body: $WAM_BODY
    #draft: false
    #skip_cleanup: true
    #file_glob: true
    #file: standalone/dist/watchmaker*
    #api_key:
    #  secure: OaLLCA68gPQOA19yNS/0dGOLODvUM5cPEtz3n0y1cyYtfEP7B5Lv9ZmjQlSO9p0nAw/0im07xn99egUAed7J45i58bXYaC+p7yBCLW6tsKdQx5Jr6nI9D+ztMlzHB2EaLLn8q7pW8uFvtUZTAi41+2DHPIYNTDBaPYzxuXhieXH4o1spXfLoLe+ETG3YLUXbaI48V55PCH7RVjHwGrJfvRjQQppyvK0580ZHc0Y914l5DdUlrDUwxMo3yp+SpJErSedqQpSaQ1OOziMinR4NtIQWrpjB0cxpOvfbsMtfMXJV54fWNT/7lOA0Xok0rHji8zttqvPrqq8C1wj8Dcj7V7N7dtmoGPKsVJ2RaVFjZ8aWPew/o7bA4S9S8NtkhJxHV3Uvn/HQrCePqCdn0T7s72XgK3FB2fZlBJwRDHBqfXVEYvFvu+85lZV2QcDeIyEZXLK6CjCSUh2GL1Du9VWFKd0VvjI34CVIRXr5wRTMTlt0KOSMBR2IxugMn1yA25Ek0M2c5e1YbO7/wZPPKPUdQJSeEyEo0XWGAp2D9zEJY5eRVkkcAY8wSbAedIWnjaieb1OR4ql3BRracFezhsF2ajmUqbiXobG26hmt2Br2cn+6bzQ7L6F43xAHsQQkJQ1w+hsyXpl7De0EbFaCfVNS+PUDV7xWrtcOfIYV/UKo2Qk=
    #on:
    #  tags: true
    #  branch: standalone
    #  repo: YakDriver/watchmaker
    #  condition: '"$TOXENV" == *"py36"*'